### ISSUE TITLE
Kills my left curly bracket

### ISSUE THREAD

**Issue by devurmel** [SergeyVinyar/VSBookmarks#1]
While using this tool i can't use the "{" from my Keyboard.
I'm using VS2013 Professional on Windows 7 SP1 Ultimate (english) 
and german Keyborad layout.
After disable VSBooksmarks every thing allright.
But with it i have that Problem.

please Review that

**Comment by SergeyVinyar** [comment]
Fixed. This bug was really specific to german keyboard layout.
Just update VSBookmarks in Visual Studio's "Extensions and updates" or build from sources (main branch).
Thank you for your bug report.
Have a nice day.
