### ISSUE TITLE
Unable to adjust keyboard shortcuts

### ISSUE THREAD

**Issue by VincentK76** [SergeyVinyar/VSBookmarks#4]
When following your instructions to change the keyboard shortcuts (ctrl-# isn't working in my installation of VS2017) I'm unable to find "VSBookmarks" in the filter under tools - customize - keyboard...  When I traverse through all the settings I also can't find the options for this extension.  

![vsbookmarks](https://user-images.githubusercontent.com/15904716/27856507-ac6b9daa-616e-11e7-8b34-d7daed43e0a1.png)

**Comment by SergeyVinyar** [comment]
Hello. Sorry for unclear instruction.
You should clear the search box at the left and type VSBookmark into an edit box called "show commands containing". You will see two sets of commands: GotobookmarkX and SetbookmarkX.
Assing Ctrl-Shift-X to GotobookmarkX and Ctrl-X to SetbookmarkX.

**Comment by SergeyVinyar** [comment]
Oops. Ctrl-Shift-X to SetbookmarkX and Ctrl-X to GotobookmarkX.
